// interactive-card-details-form/app/_components/button/index.tsx
import { twMerge } from "tailwind-merge"
import { ButtonProps } from "./buttonProps"

const Button = ({ label, className, ...props }: ButtonProps) => {
  const classNameTwMerge = twMerge(
    `grid h-[3.375rem] w-full place-content-center rounded-lg bg-very-dark-violet text-white tracking-[0.0625rem] hover:text-very-dark-violet hover:bg-transparent hover:border hover:border-very-dark-violet ${className}`,
  )
  return (
    <button className={classNameTwMerge} {...props}>
      {label}
    </button>
  )
}

export default Button

// social-links-profile/src/components/Button.svelte
<script>
	export let text = 'Click me';
  export let href = ""
  export let ariaLabel = ""
</script>

<a href={href}
  aria-label={ariaLabel}
  target="_blank"
	class="grid place-content-center bg-neutral-600 bodyBold text-neutral-000 h-[45px] w-full rounded-lg hover:bg-primary-700 hover:text-neutral-900"
	>{text}</a
>
