// conference-ticket-generator/app/_components/button/index.tsx
import { twMerge } from "tailwind-merge";
import { ButtonProps } from "./buttonProps";

const Button = ({ className, label, ...props }: ButtonProps) => {
  const classNameTw = twMerge(
    `w-full h-[3.375rem] grid place-content-center text-neutral-900 bg-orange-500 rounded-xl font-extrabold text-[19.4px]`,
    className
  );
  return (
    <button data-testid="button" className={classNameTw} {...props}>
      {label}
    </button>
  );
};

export default Button;

// social-links-profile/src/components/Button.svelte
<script>
	export let text = 'Click me';
  export let href = ""
  export let ariaLabel = ""
</script>

<a href={href}
  aria-label={ariaLabel}
  target="_blank"
	class="grid place-content-center bg-neutral-600 bodyBold text-neutral-000 h-[45px] w-full rounded-lg hover:bg-primary-700 hover:text-neutral-900"
	>{text}</a
>
