// blogr-landing-page/src/components/Footer/FooterComponent.vue
<template>
  <footer class="bg-neutral-900 rounded-se-[100px] w-full flex justify-center">
    <div
      class="max-w-[1440px] max-lg:items-center max-lg:gap-10 max-lg:py-12 w-full lg:px-[165px] px-5 mx-auto flex justify-between lg:py-[70px] lg:flex-row flex-col"
    >
      <img src="../../assets/images/logo.svg" class="w-[101px] h-10" alt="" />
      <section
        class="lg:grid flex justify-center max-lg:items-center flex-col grid-cols-[255px_255px_255px] text-neutral-0 lg:gap-[30px] gap-10"
      >
        <div class="lg:grid grid-col-[255px] gap-[21px] max-lg:text-center">
          <p class="ubuntu text-preset-4">Product</p>
          <ul class="ubuntu text-preset-6">
            <li>
              <a href="/" class="ubuntu text-preset-6 hover:underline">Overview</a>
            </li>
            <li>
              <a href="/" class="ubuntu text-preset-6 hover:underline">Pricing</a>
            </li>
            <li>
              <a href="/" class="ubuntu text-preset-6 hover:underline">Marketplace</a>
            </li>
            <li>
              <a href="/" class="ubuntu text-preset-6 hover:underline">Features</a>
            </li>
            <li>
              <a href="/" class="ubuntu text-preset-6 hover:underline">Integrations</a>
            </li>
          </ul>
        </div>

        <div class="grid grid-col-[255px] max-lg:text-center">
          <p class="ubuntu text-preset-4">Company</p>
          <ul class="pb-3">
            <li>
              <a href="/" class="ubuntu text-preset-6 hover:underline">About</a>
            </li>
            <li>
              <a href="/" class="ubuntu text-preset-6 hover:underline">Team</a>
            </li>
            <li>
              <a href="/" class="ubuntu text-preset-6 hover:underline">Blog</a>
            </li>
            <li>
              <a href="/" class="ubuntu text-preset-6 hover:underline">Careers</a>
            </li>
          </ul>
        </div>

        <div class="grid grid-col-[255px] max-lg:text-center">
          <p class="ubuntu text-preset-4">Connect</p>
          <ul class="pb-12">
            <li>
              <a href="/" class="ubuntu text-preset-6 hover:underline">Contact</a>
            </li>
            <li>
              <a href="/" class="ubuntu text-preset-6 hover:underline">Newsletter</a>
            </li>
            <li>
              <a href="/" class="ubuntu text-preset-6 hover:underline">LinkedIn</a>
            </li>
          </ul>
        </div>
      </section>
    </div>
  </footer>
</template>

// loopstudios-landing-page/src/components/Footer.svelte
<footer class="bg-black text-white w-full flex justify-center">
	<div
		class="md:px-[165px] px-[40px] py-[41px] max-w-[1440px] flex flex-col md:flex-row w-full items-center justify-between"
	>
		<nav class="flex flex-col gap-7">
			<img class="w-[144px]" src="/assets/images/logo.svg" alt="" />
			<ul class="flex flex-col md:flex-row items-center gap-[29px] pt-3 md:pt-0">
				<li>
					<a href="/" aria-label="about page">About</a>
				</li>
				<li>
					<a href="/" aria-label="careers page">Careers</a>
				</li>
				<li>
					<a href="/" aria-label="events page">Events</a>
				</li>
				<li>
					<a href="/" aria-label="products page">Products</a>
				</li>
				<li>
					<a href="/" aria-label="support page">Support</a>
				</li>
			</ul>
		</nav>

		<article class="flex flex-col gap-10 items-center md:items-end py-8 md:py-0 md:gap-7">
			<ul class="flex gap-4 items-center justify-end">
				<li>
					<a href="/" aria-label="go to facebook">
						<img src="/assets/images/icon-facebook.svg" alt="" />
					</a>
				</li>
				<li>
					<a href="/" aria-label="go to twitter">
						<img src="/assets/images/icon-twitter.svg" alt="" />
					</a>
				</li>
				<li>
					<a href="/" aria-label="go to pinterest">
						<img src="/assets/images/icon-pinterest.svg" alt="" />
					</a>
				</li>
				<li>
					<a href="/" aria-label="go to instagram">
						<img src="/assets/images/icon-instagram.svg" alt="" />
					</a>
				</li>
			</ul>
			<p class="text-center">© 2021 Loopstudios. All rights reserved.</p>
		</article>
	</div>
</footer>
