// ecommerce-product-page/app/_components/header/index.tsx
"use client";

import Image from "next/image";
import Cart from "../cart";
import { useState } from "react";

const Header = () => {
  const [cartOpen, setCartOpen] = useState(false);
  const [menuOpen, setMenuOpen] = useState(false);

  return (
    <header className="mx-auto w-full max-w-[90rem] px-5 pt-8 lg:px-[10.3125rem] lg:pt-0">
      <div className="flex w-full flex-row justify-between border-b-2 border-b-neutral-light-grayish-blue lg:pb-[1.1875rem] lg:pt-[2.5625rem]">
        <nav className="flex gap-8 md:gap-14">
          <button
            onClick={() => {
              setMenuOpen(!menuOpen);
              setCartOpen(false);
            }}
            className="flex items-start md:hidden"
          >
            <Image
              src={"/images/icon-menu.svg"}
              alt=""
              width={20}
              height={20}
              className="mt-1"
            />
          </button>

          {menuOpen && (
            <div
              className="fixed left-0 top-0 z-50 min-h-screen w-full bg-black bg-opacity-75"
              onClick={() => setMenuOpen(!menuOpen)}
            >
              <div
                className="absolute left-0 top-0 flex min-h-screen w-[50%] flex-col gap-3 bg-neutral-white px-6 py-8"
                onClick={(e) => e.stopPropagation()}
              >
                <button className="mb-8" onClick={() => setMenuOpen(!menuOpen)}>
                  <Image
                    src={"/images/icon-close.svg"}
                    alt=""
                    width={20}
                    height={20}
                  />
                </button>
                <ul className="flex flex-col gap-4">
                  <li className="relative font-bold tracking-[-0.0219rem] text-neutral-very-dark-blue">
                    <a href="/">Collections</a>
                  </li>
                  <li className="relative font-bold tracking-[-0.0219rem] text-neutral-very-dark-blue">
                    <a href="/">Men</a>
                  </li>
                  <li className="relative font-bold tracking-[-0.0219rem] text-neutral-very-dark-blue">
                    <a href="/">Women</a>
                  </li>
                  <li className="relative font-bold tracking-[-0.0219rem] text-neutral-very-dark-blue">
                    <a href="/">About</a>
                  </li>
                  <li className="relative font-bold tracking-[-0.0219rem] text-neutral-very-dark-blue">
                    <a href="/">Contact</a>
                  </li>
                </ul>
              </div>
            </div>
          )}

          <div className="relative mt-[0.125rem] h-5 w-[8.625rem]">
            <Image alt="logo" src={"/images/logo.svg"} fill />
          </div>
          <ul className="hidden gap-8 md:flex">
            <li>
              <a
                href="/"
                className="relative tracking-[-0.0219rem] text-neutral-dark-grayish-blue hover:text-neutral-very-dark-blue hover:after:absolute hover:after:-bottom-[3.125rem] hover:after:left-0 hover:after:h-[0.125rem] hover:after:w-full hover:after:bg-primary-orange"
              >
                Collections
              </a>
            </li>
            <li>
              <a
                href="/products"
                className="relative tracking-[-0.0219rem] text-neutral-dark-grayish-blue hover:text-neutral-very-dark-blue hover:after:absolute hover:after:-bottom-[3.125rem] hover:after:left-0 hover:after:h-[0.125rem] hover:after:w-full hover:after:bg-primary-orange"
              >
                Men
              </a>
            </li>

            <li>
              <a
                href="/"
                className="relative tracking-[-0.0219rem] text-neutral-dark-grayish-blue hover:text-neutral-very-dark-blue hover:after:absolute hover:after:-bottom-[3.125rem] hover:after:left-0 hover:after:h-[0.125rem] hover:after:w-full hover:after:bg-primary-orange"
              >
                Women
              </a>
            </li>
            <li>
              <a
                href="/"
                className="relative tracking-[-0.0219rem] text-neutral-dark-grayish-blue hover:text-neutral-very-dark-blue hover:after:absolute hover:after:-bottom-[3.125rem] hover:after:left-0 hover:after:h-[0.125rem] hover:after:w-full hover:after:bg-primary-orange"
              >
                About
              </a>
            </li>
            <li>
              <a
                href="/"
                className="relative tracking-[-0.0219rem] text-neutral-dark-grayish-blue hover:text-neutral-very-dark-blue hover:after:absolute hover:after:-bottom-[3.125rem] hover:after:left-0 hover:after:h-[0.125rem] hover:after:w-full hover:after:bg-primary-orange"
              >
                Contact
              </a>
            </li>
          </ul>
        </nav>

        <div className="flex gap-[2.75rem]">
          <Cart isOpen={cartOpen} setIsOpen={setCartOpen} />
          <Image
            alt=""
            src={"/images/image-avatar.png"}
            width={52}
            height={52}
            className="relative bottom-[0.9375rem] cursor-pointer hover:rounded-full hover:outline hover:outline-2 hover:outline-primary-orange"
          />
        </div>
      </div>
    </header>
  );
};

export default Header;

// loopstudios-landing-page/src/components/Header.svelte
<script lang="ts">
	let menuOpen = false;

	function toggleMenu() {
		menuOpen = !menuOpen;
		if (menuOpen) {
			document.body.classList.add('overflow-hidden');
		} else {
			document.body.classList.remove('overflow-hidden');
		}
	}
</script>

<header
	data-test-id="header"
	class="bg-no-repeat md:bg-[url('/assets/images/desktop/image-hero.jpg')] bg-[url('/assets/images/mobile/image-hero.jpg')] mx-auto bg-black text-white w-full max-w-[1440px] md:px-[165px] px-5 py-16 bg-cover h-[640px] md:h-full"
>
	<div class="flex flex-col gap-[130px] mb-[82px]">
		<nav class="flex items-center justify-between">
			<img src="/assets/images/logo.svg" class="z-50" alt="Logo" />

			<button class="md:hidden z-50" aria-label="Toggle menu" on:click={toggleMenu}>
				<img
					class="w-8 h-8 z-40"
					src={`${menuOpen ? '/assets/images/icon-close.svg' : '/assets/images/icon-hamburger.svg'}`}
					alt=""
				/>
			</button>

			<ul
				class={`items-center gap-[34px] mt-[6px] body md:flex ${menuOpen ? 'min-h-[101vh] z-40 flex flex-col absolute -top-2 left-0 w-full p-6 bg-black items-start text-start justify-center uppercase' : 'hidden'}`}
			>
				<li class={`${menuOpen ? 'self-start' : ''}`}>
					<a
						href="/"
						class={`relative hover:after:block after:hidden after:-bottom-[6px] after:-left-[-25%] after:absolute after:bg-black after:w-6 after:rounded-full after:h-[2px] ${menuOpen ? 'headingS' : ''}`}
						aria-label="about page">About</a
					>
				</li>
				<li class={`${menuOpen ? 'self-start' : ''}`}>
					<a
						href="/"
						class={`relative hover:after:block after:hidden after:-bottom-[6px] after:-left-[-25%] after:absolute after:bg-black after:w-6 after:rounded-full after:h-[2px] ${menuOpen ? 'headingS' : ''}`}
						aria-label="careers page">Careers</a
					>
				</li>
				<li class={`${menuOpen ? 'self-start' : ''}`}>
					<a
						href="/"
						class={`relative hover:after:block after:hidden after:-bottom-[6px] after:-left-[-25%] after:absolute after:bg-black after:w-6 after:rounded-full after:h-[2px] ${menuOpen ? 'headingS' : ''}`}
						aria-label="events page">Events</a
					>
				</li>
				<li class={`${menuOpen ? 'self-start' : ''}`}>
					<a
						href="/"
						class={`relative hover:after:block after:hidden after:-bottom-[6px] after:-left-[-25%] after:absolute after:bg-black after:w-6 after:rounded-full after:h-[2px] ${menuOpen ? 'headingS' : ''}`}
						aria-label="products page">Products</a
					>
				</li>
				<li class={`${menuOpen ? 'self-start' : ''}`}>
					<a
						href="/"
						class={`relative hover:after:block after:hidden after:-bottom-[6px] after:-left-[-25%] after:absolute after:bg-black after:w-6 after:rounded-full after:h-[2px] ${menuOpen ? 'headingS' : ''}`}
						aria-label="support page">Support</a
					>
				</li>
			</ul>
		</nav>

		<article
			class="p-8 pl-[39px] pb-[25px] pr-0 border border-solid border-white md:max-w-[650px] max-w-[420px] md:self-start self-center"
		>
			<h1 class="headingM pt-[6px] tracking-[0.5px]">Immersive experiences that deliver</h1>
		</article>
	</div>
</header>
