// project-tracking-intro-component/src/app/_components/header/header.component.ts
import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';

@Component({
  selector: 'header-component',
  templateUrl: './header.component.html',
  standalone: true,
  imports: [CommonModule],
})
export class HeaderComponent {
  isMenuOpen = false;

  toggleMenu() {
    this.isMenuOpen = !this.isMenuOpen;
    console.log('Menu aberto:', this.isMenuOpen);
  }
}

<header>
  <div
    class="relative z-50 max-w-[90rem] lg:px-[10.3125rem] px-5 mx-auto my-0 flex items-center w-full justify-between lg:pt-16 pt-10 lg:pb-10 pb-6"
  >
    <img src="/images/logo.svg" alt="logo" />

    <nav
      class="hidden lg:flex gap-3 items-center mt-[0.125rem] text-neutral-very-dark-blue"
    >
      <ul class="flex gap-[2.625rem] mt-[0.0625rem]">
        <li class="uppercase">
          <a
            href="/"
            class="text-[1.0625rem] font-bold lg:hover:underline lg:hover:underline-offset-2"
            >Product</a
          >
        </li>
        <li class="uppercase">
          <a
            href="/"
            class="text-[1.0625rem] font-bold lg:hover:underline lg:hover:underline-offset-2"
            >Features</a
          >
        </li>
        <li class="uppercase">
          <a
            href="/"
            class="text-[1.0625rem] font-bold lg:hover:underline lg:hover:underline-offset-2"
            >Pricing</a
          >
        </li>
      </ul>
      <div
        class="w-[0.375rem] h-[0.375rem] bg-neutral-very-dark-blue opacity-10 rounded-full mr-[2.1875rem] ml-[1.875rem]"
      ></div>
      <a
        href="/"
        class="uppercase text-neutral-grayish-blue text-[1.0625rem] font-bold lg:hover:underline lg:hover:underline-offset-2"
        >Login</a
      >
    </nav>

    <button (click)="toggleMenu()" class="lg:hidden flex">
      <img *ngIf="isMenuOpen" src="/images/icon-close.svg" alt="Close Menu" />
      <img
        *ngIf="!isMenuOpen"
        src="/images/icon-hamburger.svg"
        alt="open Menu"
      />
    </button>
    <div *ngIf="isMenuOpen" class="absolute right-0 w-full px-5">
      <nav
        *ngIf="isMenuOpen"
        class="mobile-menu lg:hidden shadow-md absolute flex bg-white p-5 rounded-lg w-[90%] top-[3.125rem]"
      >
        <ul class="text-center space-y-4 w-full">
          <li>
            <a href="/" class="text-[1.0625rem] font-bold uppercase">Product</a>
          </li>
          <li>
            <a href="/" class="text-[1.0625rem] font-bold uppercase"
              >Features</a
            >
          </li>
          <li>
            <a href="/" class="text-[1.0625rem] font-bold uppercase">Pricing</a>
          </li>
          <div
            class="w-full h-[0.0625rem] bg-neutral-very-dark-blue opacity-10 rounded-full mx-auto"
          ></div>
          <li>
            <a
              href="/"
              class="uppercase text-neutral-grayish-blue text-[1.0625rem] font-bold lg:hover:underline lg:hover:underline-offset-2"
              >Login</a
            >
          </li>
        </ul>
      </nav>
    </div>
  </div>
</header>

// ecommerce-product-page/app/_components/header/index.tsx
"use client";

import Image from "next/image";
import Cart from "../cart";
import { useState } from "react";

const Header = () => {
  const [cartOpen, setCartOpen] = useState(false);
  const [menuOpen, setMenuOpen] = useState(false);

  return (
    <header className="mx-auto w-full max-w-[90rem] px-5 pt-8 lg:px-[10.3125rem] lg:pt-0">
      <div className="flex w-full flex-row justify-between border-b-2 border-b-neutral-light-grayish-blue lg:pb-[1.1875rem] lg:pt-[2.5625rem]">
        <nav className="flex gap-8 md:gap-14">
          <button
            onClick={() => {
              setMenuOpen(!menuOpen);
              setCartOpen(false);
            }}
            className="flex items-start md:hidden"
          >
            <Image
              src={"/images/icon-menu.svg"}
              alt=""
              width={20}
              height={20}
              className="mt-1"
            />
          </button>

          {menuOpen && (
            <div
              className="fixed left-0 top-0 z-50 min-h-screen w-full bg-black bg-opacity-75"
              onClick={() => setMenuOpen(!menuOpen)}
            >
              <div
                className="absolute left-0 top-0 flex min-h-screen w-[50%] flex-col gap-3 bg-neutral-white px-6 py-8"
                onClick={(e) => e.stopPropagation()}
              >
                <button className="mb-8" onClick={() => setMenuOpen(!menuOpen)}>
                  <Image
                    src={"/images/icon-close.svg"}
                    alt=""
                    width={20}
                    height={20}
                  />
                </button>
                <ul className="flex flex-col gap-4">
                  <li className="relative font-bold tracking-[-0.0219rem] text-neutral-very-dark-blue">
                    <a href="/">Collections</a>
                  </li>
                  <li className="relative font-bold tracking-[-0.0219rem] text-neutral-very-dark-blue">
                    <a href="/">Men</a>
                  </li>
                  <li className="relative font-bold tracking-[-0.0219rem] text-neutral-very-dark-blue">
                    <a href="/">Women</a>
                  </li>
                  <li className="relative font-bold tracking-[-0.0219rem] text-neutral-very-dark-blue">
                    <a href="/">About</a>
                  </li>
                  <li className="relative font-bold tracking-[-0.0219rem] text-neutral-very-dark-blue">
                    <a href="/">Contact</a>
                  </li>
                </ul>
              </div>
            </div>
          )}

          <div className="relative mt-[0.125rem] h-5 w-[8.625rem]">
            <Image alt="logo" src={"/images/logo.svg"} fill />
          </div>
          <ul className="hidden gap-8 md:flex">
            <li>
              <a
                href="/"
                className="relative tracking-[-0.0219rem] text-neutral-dark-grayish-blue hover:text-neutral-very-dark-blue hover:after:absolute hover:after:-bottom-[3.125rem] hover:after:left-0 hover:after:h-[0.125rem] hover:after:w-full hover:after:bg-primary-orange"
              >
                Collections
              </a>
            </li>
            <li>
              <a
                href="/products"
                className="relative tracking-[-0.0219rem] text-neutral-dark-grayish-blue hover:text-neutral-very-dark-blue hover:after:absolute hover:after:-bottom-[3.125rem] hover:after:left-0 hover:after:h-[0.125rem] hover:after:w-full hover:after:bg-primary-orange"
              >
                Men
              </a>
            </li>

            <li>
              <a
                href="/"
                className="relative tracking-[-0.0219rem] text-neutral-dark-grayish-blue hover:text-neutral-very-dark-blue hover:after:absolute hover:after:-bottom-[3.125rem] hover:after:left-0 hover:after:h-[0.125rem] hover:after:w-full hover:after:bg-primary-orange"
              >
                Women
              </a>
            </li>
            <li>
              <a
                href="/"
                className="relative tracking-[-0.0219rem] text-neutral-dark-grayish-blue hover:text-neutral-very-dark-blue hover:after:absolute hover:after:-bottom-[3.125rem] hover:after:left-0 hover:after:h-[0.125rem] hover:after:w-full hover:after:bg-primary-orange"
              >
                About
              </a>
            </li>
            <li>
              <a
                href="/"
                className="relative tracking-[-0.0219rem] text-neutral-dark-grayish-blue hover:text-neutral-very-dark-blue hover:after:absolute hover:after:-bottom-[3.125rem] hover:after:left-0 hover:after:h-[0.125rem] hover:after:w-full hover:after:bg-primary-orange"
              >
                Contact
              </a>
            </li>
          </ul>
        </nav>

        <div className="flex gap-[2.75rem]">
          <Cart isOpen={cartOpen} setIsOpen={setCartOpen} />
          <Image
            alt=""
            src={"/images/image-avatar.png"}
            width={52}
            height={52}
            className="relative bottom-[0.9375rem] cursor-pointer hover:rounded-full hover:outline hover:outline-2 hover:outline-primary-orange"
          />
        </div>
      </div>
    </header>
  );
};

export default Header;
