// loopstudios-landing-page/src/components/Footer.svelte
<footer class="bg-black text-white w-full flex justify-center">
	<div
		class="md:px-[165px] px-[40px] py-[41px] max-w-[1440px] flex flex-col md:flex-row w-full items-center justify-between"
	>
		<nav class="flex flex-col gap-7">
			<img class="w-[144px]" src="/assets/images/logo.svg" alt="" />
			<ul class="flex flex-col md:flex-row items-center gap-[29px] pt-3 md:pt-0">
				<li>
					<a href="/" aria-label="about page">About</a>
				</li>
				<li>
					<a href="/" aria-label="careers page">Careers</a>
				</li>
				<li>
					<a href="/" aria-label="events page">Events</a>
				</li>
				<li>
					<a href="/" aria-label="products page">Products</a>
				</li>
				<li>
					<a href="/" aria-label="support page">Support</a>
				</li>
			</ul>
		</nav>

		<article class="flex flex-col gap-10 items-center md:items-end py-8 md:py-0 md:gap-7">
			<ul class="flex gap-4 items-center justify-end">
				<li>
					<a href="/" aria-label="go to facebook">
						<img src="/assets/images/icon-facebook.svg" alt="" />
					</a>
				</li>
				<li>
					<a href="/" aria-label="go to twitter">
						<img src="/assets/images/icon-twitter.svg" alt="" />
					</a>
				</li>
				<li>
					<a href="/" aria-label="go to pinterest">
						<img src="/assets/images/icon-pinterest.svg" alt="" />
					</a>
				</li>
				<li>
					<a href="/" aria-label="go to instagram">
						<img src="/assets/images/icon-instagram.svg" alt="" />
					</a>
				</li>
			</ul>
			<p class="text-center">© 2021 Loopstudios. All rights reserved.</p>
		</article>
	</div>
</footer>

// easybank-landing-page/src/components/footer/index.tsx
import Image from "next/image";
import RequestButton from "../requestButton";
import Link from "next/link";

const Footer = () => {
  return (
    <footer className="bg-darkBlue">
      <div className="mx-auto w-full max-w-[1440px] xl:px-[165px] px-5 py-12 flex justify-between">
        <nav className="flex items-center gap-20 w-full max-w-[660px]">
          <div className="flex flex-col h-full gap-[55px] w-full max-w-[205px]">
            <Image
              src={"/images/white-logo.svg"}
              alt=""
              width={140}
              height={120}
            />
            <ul className="flex gap-[13px] w-full mt-">
              <li>
                <Link href="/" aria-label="go to facebook page">
                  <Image
                    src={"/images/icon-facebook.svg"}
                    alt=""
                    width={20}
                    height={32}
                  />
                </Link>
              </li>
              <li>
                <Link href="/" aria-label="go to youtube page">
                  <Image
                    src={"/images/icon-youtube.svg"}
                    alt=""
                    width={20}
                    height={32}
                  />
                </Link>
              </li>
              <li>
                <Link href="/" aria-label="go to twitter page">
                  <Image
                    src={"/images/icon-twitter.svg"}
                    alt=""
                    width={20}
                    height={32}
                  />
                </Link>
              </li>
              <li>
                <Link href="/" aria-label="go to pinterest page">
                  <Image
                    src={"/images/icon-pinterest.svg"}
                    alt=""
                    width={20}
                    height={32}
                  />
                </Link>
              </li>
              <li>
                <Link href="/" aria-label="go to instagram page">
                  <Image
                    src={"/images/icon-instagram.svg"}
                    alt=""
                    width={20}
                    height={32}
                  />
                </Link>
              </li>
            </ul>
          </div>

          <ul className="flex items-start h-full text-white w-full justify-between max-w-[380px]">
            <div className="flex flex-col gap-3 w-full mt-[2px]">
              <li>
                <Link
                  href={"/"}
                  className="min-w-16 w-full"
                  aria-label="go to about us page"
                >
                  About Us
                </Link>
              </li>

              <li>
                <Link href={"/"} aria-label="go to contact page">
                  Contact
                </Link>
              </li>
              <li className="relative bottom-1">
                <Link href={"/"} aria-label="go to blog page">
                  Blog
                </Link>
              </li>
            </div>

            <div className="flex flex-col gap-3 w-full mt-[2px]">
              <li>
                <Link href={"/"} aria-label="go to careers page">
                  Careers
                </Link>
              </li>
              <li>
                <Link href={"/"} aria-label="go to support page">
                  Support
                </Link>
              </li>
              <li className="relative bottom-1">
                <Link href={"/"} aria-label="see privacy policy">
                  Privacy Policy
                </Link>
              </li>
            </div>
          </ul>
        </nav>
        <div className="flex items-end flex-col gap-6 max-w-[]">
          <div>
            <RequestButton />
          </div>
          <p className="bodyMd tracking-tight">
            © Easybank. All Rights Reserved
          </p>
        </div>
      </div>
    </footer>
  );
};

export default Footer;
