// easybank-landing-page/src/app/page.tsx
import Header from "../components/header";
import Footer from "@/components/footer/";
import WhyChooseEasyBank from "@/components/whyChooseEasyBank";
import LatestArticles from "@/components/latestArticles";

export default function Home() {
  return (
    <>
      <Header />
      <main>
        <WhyChooseEasyBank />
        <LatestArticles />
      </main>
      <Footer />
    </>
  );
}

// blogr-landing-page/src/App.vue
<script setup lang="ts">
import HeaderComponent from './components/Header/HeaderComponent.vue'
import FooterComponent from './components/Footer/FooterComponent.vue'
import InfrastructureSection from './components/InfrastructureSection/InfrastructureSection.vue'
import FeatureWithIllustration from './components/FeatureWithIllustration/FeatureWithIllustration.vue'
import FeatureHighlight from './components/FeatureHighlight/FeatureHighlight.vue'
</script>

<template>
  <HeaderComponent />

  <main>
    <FeatureHighlight />
    <InfrastructureSection />
    <FeatureWithIllustration />
  </main>

  <FooterComponent />
</template>

<style scoped>
header {
  line-height: 1.5;
}
</style>
